BEGIN;


DROP TABLE IF EXISTS "categorie", "ingredient", "recette", "recetteIngredient";


CREATE TABLE "categorie" (
  "id"          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name"        TEXT NOT NULL,  
  "created_at"  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"  TIMESTAMPTZ
);

CREATE TABLE "ingredient" (
  "id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "macro" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "recette" (
    "id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "description" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "category_id" INTEGER,
    "ingredient_id" INTEGER NOT NULL,
    "macro" TEXT NOT NULL,
    "image" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "recetteIngredient" (
  -- "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recette_id" integer NOT NULL REFERENCES "recette"("id"),
  "ingredient_id" integer NOT NULL REFERENCES "ingredient"("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz,
  PRIMARY KEY (recette_id, ingredient_id)
  
);

ALTER TABLE "recette" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredient"("id");
ALTER TABLE "recette" ADD FOREIGN KEY ("category_id") REFERENCES "categorie"("id");
-- ALTER TABLE "recetteIngredient" ADD FOREIGN KEY ("recette_id") REFERENCES "recette"("id");
-- ALTER TABLE "recetteIngredient" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredient"("id");
-- INSERT INTO "recetteIngredient" ("recette_id","ingredient_id") VALUES (1,1);




COMMIT;